### PR TITLE
*** Updated showing options ***

### PR DESCRIPTION
**Pull request by OnurVar**

### CODE REVIEW

**Comment by nimati** [comment]
Hey,
Just wondering what the new showing options are for?

**Comment by OnurVar** [comment]
Hello,

Current method "showAlertInView" is just using  UIViewController and its view's window (view.view.window). 

With these extra method, you can also show alertview (using "showAlertInWindow" ) on any window you sent (it can be UIApplication.sharedApplications.ketWindow), or show on any alert on UIApplication.sharedApplications.ketWindow automatically using "showAlertWithTitle"

So there is no dependency to call alertview on UIViewController. You can even call it on non-UI related classes.

**Comment by nimati** [comment]
Hey,

Hmm interesting. With your version, could you also test to see if it fixes this issue with the keyboard:
https://github.com/nimati/FCAlertView/issues/11 

It's related to this as well
Let me know,
Cheers!

**Comment by nimati** [comment]
Hey Onur,

Tested your commit, works nice. Great work, I will also fix issue #11 on top of your commit. 

Cheers! 👍 @onurvarrrr

**Pull request merged**
